#compiler 
CC      = arm-linux-gnueabihf-gcc
# Include directory 
INC_DIR = ..
INC_LIB = 

# libraries 

# Compilation flags 
CFLAGS = -std=c99 \
	        -g -I${INC_DIR} \
		-pedantic \
		-Wall \
		-W \
		-Wmissing-prototypes \
		-Wno-sign-compare \
		-Wno-unused-parameter
		
#####################################################


RM      = rm -f

BIN = client

all:  $(BIN)

clean:
	$(RM)  $(BIN)
    
    
    
    

